### ISSUE TITLE
Don´t work with Mac OS X 10.11.6 and SqlDeveloper 4.1.3

### ISSUE THREAD

**Issue by darioajr** [scristalli/sql-developer-keepalive#18]
don ´t show icon.

**Comment by lylehenderson** [comment]
I just installed this on Linux for SqlDeveloper 4.1.3.20 and I also don't see an icon anywhere.
However, I might not know where to look, since the help page just says "Click icon".

**Comment by scristalli** [comment]
You are looking for the first icon from the right in the image.

![keepalive-icon](https://user-images.githubusercontent.com/7326295/72891109-c65edc80-3d13-11ea-8a57-853c63788f9c.png)

**Comment by faradoxuz** [comment]
Move your SqlDeveloper to Application folder
