### ISSUE TITLE
Silently failed install on Version 4.2.0.17.089

### ISSUE THREAD

**Issue by joncarmignani** [scristalli/sql-developer-keepalive#23]
I got through the install from local file and was prompted to restart cleanly.  Upon restart, however, I do not have a keepalive icon as stated in the installation instructions.

I can provide logging info if someone tells me where to find it.

**Comment by scristalli** [comment]
I know these are old issues; just for future reference: first icon from the right.
keepalive works for me with version 19.2.1.247

![keepalive-icon](https://user-images.githubusercontent.com/7326295/72891478-9d8b1700-3d14-11ea-9b1e-6b41f9e49fc8.png)
