### ISSUE TITLE
sql dev wont open

### ISSUE THREAD

**Issue by devsd1** [scristalli/sql-developer-keepalive#24]
Installed the .jar via SQL Developer (4.1.3).  Upon restarting the app, it starts to load and gets to maybe 10%, then quits.  Neither rebooting nor removing keepalive helps.   Can I load SQL Dev without any extensions?  How do I completely remove keepalive?

**Comment by alfabravoteam** [comment]
Tested this on v19 and it shows the same behavior.

**Comment by scristalli** [comment]
You should not use a JAR file to install the extension; you should rather use the ZIP file, please read the [wiki](https://github.com/scristalli/sql-developer-keepalive/wiki).
