### ISSUE TITLE
Where is the KeepAlive Icon in SQL Developer After Installation

### ISSUE THREAD

**Issue by khalidmehmood** [scristalli/sql-developer-keepalive#25]
I have installed the KeepAlive extension successfully. 

_One problem was faced during installation as the paths were not correct within zip file. The actual contents of the folder were selected and then again compressed which resulted in correct installable zip file._

**Later after installation I am unable to find where is the KeepAlive option in SQL Developer. Is it specific to a connection or just for Queries?**

Need help here.

**Comment by jessebax** [comment]
I am also do not see the icon after installing in SQLDeveloper Version 18.2.0.183

**Comment by scristalli** [comment]
You are looking for the first icon from the right in the image. If you had problems with the installation, you should provide more information (keepalive works for me with version 19.2.1.247).

![keepalive-icon](https://user-images.githubusercontent.com/7326295/72891196-002fe300-3d14-11ea-92f7-6fc448805bf5.png)
