### ISSUE TITLE
Can't install the extension. Is it not supposed to work on my version?

### ISSUE THREAD

**Issue by alexandis** [scristalli/sql-developer-keepalive#29]
![Annotation 2020-05-27 192657](https://user-images.githubusercontent.com/6149843/83046880-4ee9e280-a050-11ea-8fc1-e4afe210e52e.png)
**Oracle SQL Developer 19.4.0.354**
Sorry - used 'development' version before :) Now everything is fine, thanx.

**Comment by alexandis** [comment]
But is it possible to remove "Connection has been reset" dialog which pops up anyway?

**Comment by scristalli** [comment]
@alexandis could you please post a picture of such dialog and say when it appears? Maybe in a separate issue, so we track that improvement/bug/feature request better. Thank you.

**Comment by alexandis** [comment]
@scristalli Ok. So when I set up the extension and leave my computer unattended - after polling interval passed (probably), I get this:
![image](https://user-images.githubusercontent.com/6149843/83075788-17455f80-a07d-11ea-8707-abd774d073c8.png)
I click "OK" to close the popup - but then I see the previous one, close it - and have to close the before-previous... :) Seems like each time polling happens, a new popup is shown...

**Comment by scristalli** [comment]
@alexandis that's not supposed to happen, certainly I would not expect the extension to cause this behavior. Please open a new issue to track this, so we can confirm and figure out the problem.

**Comment by alexandis** [comment]
@scristalli thanx: [https://github.com/scristalli/sql-developer-keepalive/issues/30](url)
