### ISSUE TITLE
Popup dialog is shown EACH time polling happens

### ISSUE THREAD

**Issue by alexandis** [scristalli/sql-developer-keepalive#30]
When I set up the extension and leave my computer unattended - after polling interval passed (probably), I get this:
![Annotation 2020-06-03 194206](https://user-images.githubusercontent.com/6149843/83664228-6259f800-a5d2-11ea-9413-1fc27c93c021.png)
I click "OK" to close the popup - but then I see the previous one, close it - and have to close the before-previous... Seems like each time polling happens, a new popup is shown.
**Oracle SQL Developer 19.4.0.354**

**Comment by camcco05** [comment]
@alexandis, I'm getting the same error.  Thank you for posting this!

**Comment by bertbert72** [comment]
The popup should only appear when a connection is being re-established, so this would imply that the connection is being lost before the keep-alive fires.  In that case you could easily get several popups - it's not the plug-in that shows these, it's SQL Developer itself.  Try making the polling interval smaller and see if this helps.

**Comment by alexandis** [comment]
> The popup should only appear when a connection is being re-established, so this would imply that the connection is being lost before the keep-alive fires. In that case you could easily get several popups - it's not the plug-in that shows these, it's SQL Developer itself. Try making the polling interval smaller and see if this helps.

Yeap, you are right, I guess. And it did help - so before remote connection was closed according to remote settings which I cannot control - "Keep alive" was triggered. I personally chose 5 min.
