### ISSUE TITLE
zip not contain a bundle manifest in META-INF/bundle.xml

### ISSUE THREAD

**Issue by camcco05** [scristalli/sql-developer-keepalive#31]
scristalli,

I tried installing the sql-developer-keepalive-master.zip on both my PC and Mac using "Check for Updates" >> Install From Local Files >> PATH and file: sql-developer-keepalive-master.zip and I keep getting the following error:

"Zip file sql-developer-keepalive-master.zip does not contain a bundle manifest in META-INF/bundle.xml."

Can you all help?

Thanks so much and I look forward to hearing back from you!

**Comment by scristalli** [comment]
@camcco05 it looks like you might be using the ZIP file containing the Git repo. Could you please try using the latest file from the [Releases page](https://github.com/scristalli/sql-developer-keepalive/releases) instead?

**Comment by camcco05** [comment]
@scristalli, WOW that fixed it!  Could you make a note about it on your page?  Thank you so much for all the help and developing this app!! :)
