### ISSUE TITLE
Unable to install extension 

### ISSUE THREAD

**Issue by JitApex** [scristalli/sql-developer-keepalive#32]
Hi,

I have tried to install the extension multiple times but hitting this issue - it is unable to locate the META-INF/bundle.xml under the zip.  I verified manually the file and folder exist.

bundle.xml - 
<update-bundle version="1.3.0" 
	xmlns="http://xmlns.oracle.com/jdeveloper/updatebundle" 
	xmlns:u="http://xmlns.oracle.com/jdeveloper/update">
	<u:update id="keepalive">
		<u:name>keepalive</u:name>
		<u:version>1.3.1</u:version>
		<u:author>Stefano Cristalli</u:author>
		<u:author-url>http://scristalli.altervista.org</u:author-url>
		<u:description>keepalive extension for Oracle SQL Developer 4+.</u:description>
    </u:update>
</update-bundle>

![image](https://user-images.githubusercontent.com/38888464/84859906-ad244700-b08b-11ea-802d-a4cdf5979942.png)

SQL Developer version - 18.3

**Comment by JitApex** [comment]
Just an update after giving direct path  to META-INF under zip , I am able to load the extension but unable to see any extension  icon after restart

**Comment by scristalli** [comment]
Please refer to issue #31.

**Comment by JitApex** [comment]
thanks it worked.
