### ISSUE TITLE
Keepalive not working with SQL Developer v20.2.0.175?

### ISSUE THREAD

**Issue by gdevelekos** [scristalli/sql-developer-keepalive#35]
I installed it two ways: 

1. Using the "get updates" and then importing the .zip file
2. downloading the .jar file and putting it in SQLDEV_HOME/sqldeveloper/extentions

Both ways, after I restart, there is no button on the menu (as there is on my office PC where I use an older SQL_DEV version). There is also no "keep-alive" menu when I right-click on a connection.

Please advise.

**Comment by dhauverNS** [comment]
@gdevelekos I had a similar problem. I was trying to install to SQL Developer 18.1 running on Windows 10 and experienced the same problems as you. I was able to finally get it to install by running SQL Developer as an administrator and then importing the zip file through the "get updates" dialog. This finally allowed the extension to install and show up in the UI.

**Comment by gdevelekos** [comment]
Your trick worked for me, thank  you!

**Comment by scristalli** [comment]
Sorry for missing the notifications on this, glad it was resolved.

**Comment by mycahmason** [comment]
I just tried installing this on Windows 10, Oracle SQL Developer 19.1.0.094 (Build 094.2042) and the icon didn't show up at first, but running SQL Developer as Admin worked for me and it is keeping my session alive.

Thank you!
